export const ADD_CART_PRODUCT = "ADD_CART_PRODUCT";
export const DELETE_CART_PRODUCT = "DELETE_CART_PRODUCT";
export const INCREASE_CART_PRODUCT = "INCREASE_CART_PRODUCT";
export const DECREASE_CART_PRODUCT = "DECREASE_CART_PRODUCT";
export const TOTAL_AMOUNT = "TOTAL_AMOUNT";